USE vaccines;
SELECT * 
FROM covarage
WHERE GROUP_NAME = "WHO_REGIONS"
;
CREATE VIEW covarage_global as (SELECT *
							FROM covarage
							WHERE GROUP_NAME = "WHO_REGIONS");
                            
CREATE VIEW cases_global as (SELECT *
							FROM cases
							WHERE GROUP_NAME = "WHO_REGIONS");


SELECT *
FROM covarage_global
WHERE DOSES IS NULL;

SELECT COUNT(YEAR)
FROM covarage_global
WHERE DOSES IS NULL;

SELECT COUNT(YEAR)
FROM cases_global;




SELECT DISTINCT(CODE) FROM cases_global;
SELECT DISTINCT(WHO_REGION) FROM vaccine;
UPDATE vaccine
SET WHO_REGION = "EMR"
WHERE WHO_REGION = "EMRO";

UPDATE vaccine
SET WHO_REGION = "AFR"
WHERE WHO_REGION = "AFRO";

UPDATE vaccine
SET WHO_REGION = "EUR"
WHERE WHO_REGION = "EURO";

UPDATE vaccine
SET WHO_REGION = "AMR"
WHERE WHO_REGION = "AMRO";

UPDATE vaccine
SET WHO_REGION = "WPR"
WHERE WHO_REGION = "WPRO";

UPDATE vaccine
SET WHO_REGION = "SEAR"
WHERE WHO_REGION = "SEARO";

SELECT * FROM cases;
SELECT * FROM cases_global;
SELECT * FROM covarage;
SELECT * FROM covarage_global;
SELECT DISTINCT(ANTIGEN_DESCRIPTION) FROM covarage;
SELECT DISTINCT(ANTIGEN) FROM covarage;
SELECT DISTINCT(DISEASE) FROM cases_global;

SELECT DISEASE_DESCRIPTION,YEAR, SUM(CASES) as total
FROM cases_global
GROUP BY YEAR, DISEASE_DESCRIPTION
ORDER BY DISEASE_DESCRIPTION, YEAR
LIMIT 5;

SELECT c.DISEASE_DESCRIPTION, c.YEAR, SUM(c.CASES) AS total
FROM cases_global c
JOIN (
    SELECT DISEASE_DESCRIPTION, MAX(YEAR) AS max_year
    FROM cases_global
    GROUP BY DISEASE_DESCRIPTION
) AS sub ON c.DISEASE_DESCRIPTION = sub.DISEASE_DESCRIPTION
WHERE c.YEAR >= sub.max_year - 9
GROUP BY c.DISEASE_DESCRIPTION, c.YEAR
ORDER BY c.DISEASE_DESCRIPTION, c.YEAR;
